config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    collection do
      get :tags
    end
  end

  namespace :admin do
    root 'top#index'
    devise_for :admin_users, controllers: {
        registrations: 'admin/admin_user/registrations',
        sessions: 'admin/admin_user/sessions'
    }
    resources :posts do
      collection do
        post :preview
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  STATUS_PRIVATE = 'private'.freeze
  STATUS_PUBLIC = 'public'.freeze
  STATUS_VALUES = [STATUS_PRIVATE, STATUS_PUBLIC].map(&:freeze).freeze


  validates :title, presence: true, length: {maximum: 200}
  validates :body, :posted_at, presence: true
  validates :status, inclusion: {in: STATUS_VALUES}

  scope :common, -> {where('status = ? AND posted_at <= ?', STATUS_PUBLIC, Time.now)}
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController

  def index
    @posts = Post.all.order(posted_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    p @post
  end

  def create
    @post = Post.new(post_params)
    @post.tag_list = params[:post][:tag_list]
    if params[:preview_button]
      render template: 'admin/posts/preview'
    elsif @post.save
      redirect_to [:admin, @post], notice: '投稿を作成しました。'
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    @post.tag_list = params[:post][:tag_list]
    if params[:preview_button]
      render template: 'admin/posts/preview'
    elsif @post.save
      redirect_to [:admin, @post], notice: '投稿を更新しました。'
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :admin_posts, notice: '投稿を削除しました。'
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :posted_at, :status)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_all_tags, only: [:index, :tags]

  def index
    @posts = Post.common.order(posted_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def tags
    if view_context.parameter_tag_list.present?
      @posts = Post.common
                   .order(posted_at: :desc)
                   .page(params[:page])
                   .tagged_with(view_context.parameter_tag_list, any: true)
      render :index
    else
      redirect_to action: 'index'
    end
  end

  private

  def set_all_tags
    @all_tags = ActsAsTaggableOn::Tag.all.map { |tag| tag.name }
  end
end

app/views/posts/_post.html.erb
<% if post.present? %>
  <div class="post">
    <div class="post_header">
      <h2 class="title">
        <%= link_to_unless_current post.title, post, class: 'post' %>
      </h2>
      <%= fa_icon 'clock-o' %><p class="posted_at"><%= post.posted_at.strftime('%Y.%m.%d') %></p>
      <%= render 'posts/tags', tag_list: post.tag_list %>
    </div>
    <div class="post_body">
      <div class="markdown_view">
        <% if detailed %>
          <%= markdown post.body %>
        <% else %>
          <%= markdown truncate(post.body.html_safe, length: 200, omission: '...') %>
        <% end %>
      </div>
    </div>
    <%= link_to '続きを読む...', post, class: 'read_more' unless detailed %>
  </div>
<% end %>

app/views/posts/_tags.html.erb
<% if tag_list.present? %>
  <ul class="tags">
    <% tag_list.each_with_index do |tag| %>
      <li class="tag <%= tag %>">
        <%= link_to tag, tags_posts_path(tag_list: (parameter_tag_list | [tag])) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/index.html.erb
<% if @posts.present? %>
  <% if parameter_tag_list.present? %>
    <div class="refine_post">
      <ul class="tags">
        <% parameter_tag_list.each do |refine_tag| %>
          <li><%= link_to tags_posts_path(tag_list: (parameter_tag_list - [refine_tag])) do %>
              <span> <%= "× #{refine_tag}" %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% @posts.each do |post| %>
    <%= render partial: 'posts/post', locals: {post: post, detailed: false} %>
  <% end %>
  <%= paginate @posts %>
<% else %>
  <p>記事が存在しません。</p>
<% end %>

app/views/posts/show.html.erb
<% @page_title = @post.title %>
<%= render partial: 'posts/post', locals: {post: @post, detailed: true} %>
<%= link_to '戻る', :back %>